<?php
// Extracted full list of country codes, with Tunisia pinned at the top
$whatsapp_code = isset($whatsapp_code) ? $whatsapp_code : '+216';

$countries = [
    // Pinned
    ['code' => '+216', 'name' => 'Tunisie (+216)'],
    ['code' => 'disabled', 'name' => '──────────'],
    // Ordered Alphabetically by French Name
    ['code' => '+93', 'name' => 'Afghanistan (+93)'],
    ['code' => '+355', 'name' => 'Albanie (+355)'],
    ['code' => '+213', 'name' => 'Algérie (+213)'],
    ['code' => '+49', 'name' => 'Allemagne (+49)'],
    ['code' => '+376', 'name' => 'Andorre (+376)'],
    ['code' => '+244', 'name' => 'Angola (+244)'],
    ['code' => '+966', 'name' => 'Arabie saoudite (+966)'],
    ['code' => '+54', 'name' => 'Argentine (+54)'],
    ['code' => '+374', 'name' => 'Arménie (+374)'],
    ['code' => '+61', 'name' => 'Australie (+61)'],
    ['code' => '+43', 'name' => 'Autriche (+43)'],
    ['code' => '+994', 'name' => 'Azerbaïdjan (+994)'],
    ['code' => '+973', 'name' => 'Bahreïn (+973)'],
    ['code' => '+880', 'name' => 'Bangladesh (+880)'],
    ['code' => '+32', 'name' => 'Belgique (+32)'],
    ['code' => '+229', 'name' => 'Bénin (+229)'],
    ['code' => '+591', 'name' => 'Bolivie (+591)'],
    ['code' => '+387', 'name' => 'Bosnie-Herzégovine (+387)'],
    ['code' => '+55', 'name' => 'Brésil (+55)'],
    ['code' => '+359', 'name' => 'Bulgarie (+359)'],
    ['code' => '+226', 'name' => 'Burkina Faso (+226)'],
    ['code' => '+257', 'name' => 'Burundi (+257)'],
    ['code' => '+855', 'name' => 'Cambodge (+855)'],
    ['code' => '+237', 'name' => 'Cameroun (+237)'],
    ['code' => '+1', 'name' => 'Canada (+1)'],
    ['code' => '+238', 'name' => 'Cap-Vert (+238)'],
    ['code' => '+236', 'name' => 'Centrafrique (+236)'],
    ['code' => '+56', 'name' => 'Chili (+56)'],
    ['code' => '+86', 'name' => 'Chine (+86)'],
    ['code' => '+357', 'name' => 'Chypre (+357)'],
    ['code' => '+57', 'name' => 'Colombie (+57)'],
    ['code' => '+269', 'name' => 'Comores (+269)'],
    ['code' => '+242', 'name' => 'Congo-Brazzaville (+242)'],
    ['code' => '+243', 'name' => 'Congo-Kinshasa (+243)'],
    ['code' => '+82', 'name' => 'Corée du Sud (+82)'],
    ['code' => '+506', 'name' => 'Costa Rica (+506)'],
    ['code' => '+225', 'name' => 'Côte d\'Ivoire (+225)'],
    ['code' => '+385', 'name' => 'Croatie (+385)'],
    ['code' => '+53', 'name' => 'Cuba (+53)'],
    ['code' => '+45', 'name' => 'Danemark (+45)'],
    ['code' => '+253', 'name' => 'Djibouti (+253)'],
    ['code' => '+20', 'name' => 'Égypte (+20)'],
    ['code' => '+971', 'name' => 'Émirats arabes unis (+971)'],
    ['code' => '+593', 'name' => 'Équateur (+593)'],
    ['code' => '+34', 'name' => 'Espagne (+34)'],
    ['code' => '+372', 'name' => 'Estonie (+372)'],
    ['code' => '+1', 'name' => 'États-Unis (+1)'],
    ['code' => '+251', 'name' => 'Éthiopie (+251)'],
    ['code' => '+358', 'name' => 'Finlande (+358)'],
    ['code' => '+33', 'name' => 'France (+33)'],
    ['code' => '+241', 'name' => 'Gabon (+241)'],
    ['code' => '+220', 'name' => 'Gambie (+220)'],
    ['code' => '+995', 'name' => 'Géorgie (+995)'],
    ['code' => '+233', 'name' => 'Ghana (+233)'],
    ['code' => '+30', 'name' => 'Grèce (+30)'],
    ['code' => '+224', 'name' => 'Guinée (+224)'],
    ['code' => '+245', 'name' => 'Guinée-Bissau (+245)'],
    ['code' => '+509', 'name' => 'Haïti (+509)'],
    ['code' => '+504', 'name' => 'Honduras (+504)'],
    ['code' => '+36', 'name' => 'Hongrie (+36)'],
    ['code' => '+91', 'name' => 'Inde (+91)'],
    ['code' => '+62', 'name' => 'Indonésie (+62)'],
    ['code' => '+964', 'name' => 'Irak (+964)'],
    ['code' => '+98', 'name' => 'Iran (+98)'],
    ['code' => '+353', 'name' => 'Irlande (+353)'],
    ['code' => '+354', 'name' => 'Islande (+354)'],
    ['code' => '+972', 'name' => 'Israël (+972)'],
    ['code' => '+39', 'name' => 'Italie (+39)'],
    ['code' => '+1876', 'name' => 'Jamaïque (+1876)'],
    ['code' => '+81', 'name' => 'Japon (+81)'],
    ['code' => '+962', 'name' => 'Jordanie (+962)'],
    ['code' => '+7', 'name' => 'Kazakhstan (+7)'],
    ['code' => '+254', 'name' => 'Kenya (+254)'],
    ['code' => '+965', 'name' => 'Koweït (+965)'],
    ['code' => '+961', 'name' => 'Liban (+961)'],
    ['code' => '+218', 'name' => 'Libye (+218)'],
    ['code' => '+352', 'name' => 'Luxembourg (+352)'],
    ['code' => '+261', 'name' => 'Madagascar (+261)'],
    ['code' => '+60', 'name' => 'Malaisie (+60)'],
    ['code' => '+223', 'name' => 'Mali (+223)'],
    ['code' => '+356', 'name' => 'Malte (+356)'],
    ['code' => '+212', 'name' => 'Maroc (+212)'],
    ['code' => '+230', 'name' => 'Maurice (+230)'],
    ['code' => '+222', 'name' => 'Mauritanie (+222)'],
    ['code' => '+52', 'name' => 'Mexique (+52)'],
    ['code' => '+373', 'name' => 'Moldavie (+373)'],
    ['code' => '+377', 'name' => 'Monaco (+377)'],
    ['code' => '+258', 'name' => 'Mozambique (+258)'],
    ['code' => '+95', 'name' => 'Myanmar (Birmanie) (+95)'],
    ['code' => '+264', 'name' => 'Namibie (+264)'],
    ['code' => '+977', 'name' => 'Népal (+977)'],
    ['code' => '+505', 'name' => 'Nicaragua (+505)'],
    ['code' => '+227', 'name' => 'Niger (+227)'],
    ['code' => '+234', 'name' => 'Nigeria (+234)'],
    ['code' => '+47', 'name' => 'Norvège (+47)'],
    ['code' => '+64', 'name' => 'Nouvelle-Zélande (+64)'],
    ['code' => '+968', 'name' => 'Oman (+968)'],
    ['code' => '+256', 'name' => 'Ouganda (+256)'],
    ['code' => '+998', 'name' => 'Ouzbékistan (+998)'],
    ['code' => '+92', 'name' => 'Pakistan (+92)'],
    ['code' => '+970', 'name' => 'Palestine (+970)'],
    ['code' => '+507', 'name' => 'Panama (+507)'],
    ['code' => '+595', 'name' => 'Paraguay (+595)'],
    ['code' => '+31', 'name' => 'Pays-Bas (+31)'],
    ['code' => '+51', 'name' => 'Pérou (+51)'],
    ['code' => '+63', 'name' => 'Philippines (+63)'],
    ['code' => '+48', 'name' => 'Pologne (+48)'],
    ['code' => '+351', 'name' => 'Portugal (+351)'],
    ['code' => '+974', 'name' => 'Qatar (+974)'],
    ['code' => '+420', 'name' => 'République Tchèque (+420)'],
    ['code' => '+40', 'name' => 'Roumanie (+40)'],
    ['code' => '+44', 'name' => 'Royaume-Uni (+44)'],
    ['code' => '+7', 'name' => 'Russie (+7)'],
    ['code' => '+250', 'name' => 'Rwanda (+250)'],
    ['code' => '+221', 'name' => 'Sénégal (+221)'],
    ['code' => '+381', 'name' => 'Serbie (+381)'],
    ['code' => '+248', 'name' => 'Seychelles (+248)'],
    ['code' => '+65', 'name' => 'Singapour (+65)'],
    ['code' => '+421', 'name' => 'Slovaquie (+421)'],
    ['code' => '+386', 'name' => 'Slovénie (+386)'],
    ['code' => '+252', 'name' => 'Somalie (+252)'],
    ['code' => '+249', 'name' => 'Soudan (+249)'],
    ['code' => '+94', 'name' => 'Sri Lanka (+94)'],
    ['code' => '+46', 'name' => 'Suède (+46)'],
    ['code' => '+41', 'name' => 'Suisse (+41)'],
    ['code' => '+963', 'name' => 'Syrie (+963)'],
    ['code' => '+992', 'name' => 'Tadjikistan (+992)'],
    ['code' => '+886', 'name' => 'Taïwan (+886)'],
    ['code' => '+255', 'name' => 'Tanzanie (+255)'],
    ['code' => '+66', 'name' => 'Thaïlande (+66)'],
    ['code' => '+228', 'name' => 'Togo (+228)'],
    ['code' => '+90', 'name' => 'Turquie (+90)'],
    ['code' => '+380', 'name' => 'Ukraine (+380)'],
    ['code' => '+598', 'name' => 'Uruguay (+598)'],
    ['code' => '+58', 'name' => 'Venezuela (+58)'],
    ['code' => '+84', 'name' => 'Vietnam (+84)'],
    ['code' => '+967', 'name' => 'Yémen (+967)'],
    ['code' => '+260', 'name' => 'Zambie (+260)'],
    ['code' => '+263', 'name' => 'Zimbabwe (+263)']
];

foreach ($countries as $country) {
    if ($country['code'] === 'disabled') {
        echo '<option disabled>' . htmlspecialchars($country['name']) . '</option>';
    } else {
        $selected = ($whatsapp_code === $country['code']) ? 'selected' : '';
        echo '<option value="' . htmlspecialchars($country['code']) . '" ' . $selected . '>' . htmlspecialchars($country['name']) . '</option>';
    }
}
?>
